---
- hosts: tag_Name_cdk_nginx
- name: nginx assignment
  import_playbook: ../static-assignments/nginx.yml

- hosts: tag_Name_cdk_tooling
- name: tooling assignment
  import_playbook: ../static-assignments/tooling.yml

- hosts: tag_Name_cdk_wordpress
- name: wordpress assignment
  import_playbook: ../static-assignments/wordpress.yml

# - hosts: tag_Name_CDK_jenkins
# - name: jenkins assignment
#   import_playbook: ../static-assignments/jenkins.yml

# - hosts: tag_Name_CDK_artifactory
# - name: artifactory assignment
#   import_playbook: ../static-assignments/jfrog.yml

# - hosts: tag_Name_CDK_sonarqube
#   user: ubuntu
# - name: sonarqube assignment
#   import_playbook: ../static-assignments/sonar.yml