- name: Ensure pip3 is installed
  yum:
    name: python3-pip
    state: present
  become: yes
  when: ansible_os_family == "RedHat"

- name: Install PyMySQL
  pip:
    name: pymysql
    state: present

- name: create database
  community.mysql.mysql_db:
    login_host: "citatech-database.cb42aocm8t1r.eu-central-1.rds.amazonaws.com"
    login_user: "citatech"
    login_password: "devopspbl"
    name: wordpressdb
    collation: utf8_general_ci
    encoding: utf8
    state: present


- name: Input wordpress credentials
  ansible.builtin.replace:
    path: /var/www/html/wp-config.php
    regexp: "{{ item.regexp }}"
    replace: "{{ item.line }}"
  loop:
    - { regexp: '^localhost', line: "citatech-database.cb42aocm8t1r.eu-central-1.rds.amazonaws.com" }
    - { regexp: '^username_here', line: "citatech" }
    - { regexp: '^database_name_here', line: "wordpressdb" }
    - { regexp: '^password_here', line: "devopspbl" }
