- name: Ensure pip3 is installed
  yum:
    name: python3-pip
    state: present
  become: yes
  when: ansible_os_family == "RedHat"

- name: Install PyMySQL
  pip:
    name: pymysql
    state: present

- name: create database
  community.mysql.mysql_db:
    login_host: "mwangiii-database.clagwoeu40nj.eu-central-1.rds.amazonaws.com"
    login_user: "mwangiii"
    login_password: "devopspbl"
    name: toolingdb
    collation: utf8_general_ci
    encoding: utf8
    state: present

- name: Input tooling credentials
  ansible.builtin.replace:
    path: /var/www/html/functions.php
    regexp: "{{ item.regexp }}"
    replace: "{{ item.line }}"
  loop:
    - {
        regexp: "^mysql.tooling.svc.cluster.local",
        line: "mwangiii-database.clagwoeu40nj.eu-central-1.rds.amazonaws.com",
      }
    - { regexp: "^admin", line: "mwangiii" }
    - { regexp: "^tooling", line: "toolingdb" }
    - { regexp: "^admin", line: "devopspbl" }
